### ISSUE TITLE
Why are the outputs of discriminator not 0/1-value?

### ISSUE THREAD

**Issue by eggachecat** [ratschlab/RGAN#19]
HI, guys, 
Thanks for your great job!

When I go though your code, I notice that the output of discriminator seemed not to be 0/1 but a 0/1 - matrix? Why is that ? Is it heuristic way? 
Thanks a lot.

```python
# from line 316 model.py line 
#      logit_final = tf.matmul(rnn_outputs[:, -1], W_final_D) + b_final_D
        logits = tf.einsum('ijk,km', rnn_outputs, W_out_D) + b_out_D
#      rnn_outputs_flat = tf.reshape(rnn_outputs, [-1, hidden_units_d])
#      logits = tf.matmul(rnn_outputs_flat, W_out_D) + b_out_D
```

**Comment by corcra** [comment]
If I understand your question correctly, the discriminator makes predictions at every time point. But since we operate on batches at a time, the output is then matrix-shaped.
