### ISSUE TITLE
Error running experiment.py

### ISSUE THREAD

**Issue by pedrofale** [ratschlab/RGAN#2]
Hello, I am trying to run experiment.py but I am getting this error:

`Traceback (most recent call last):
  File "experiment.py", line 9, in <module>
    import data_utils
  File "RGAN/data_utils.py", line 9, in <module>
    import model
  File "RGAN/model.py", line 7, in <module>
    from mod_core_rnn_cell_impl import LSTMCell          #modified to allow initializing bias in lstm
  File "RGAN/mod_core_rnn_cell_impl.py", line 45, in <module>
    from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
ImportError: cannot import name '_RNNCell'`

**Comment by corcra** [comment]
Hmm, which version of tensorflow do you have installed?

**Comment by pedrofale** [comment]
Using the original LSTMCell "solved" it.

**Comment by ArturoDeza** [comment]
@pedrofale what was this workaround in terms of code? Bumped into the same issue.

**Comment by pedrofale** [comment]
Commenting out line 7 in `model.py` and uncommenting in line 8. I am using TensorFlow v1.2.1.

**Comment by ArturoDeza** [comment]
Works perfect now and is finally running. Still going over code and studying it. Btw, do you happen to know if doing the line modification you mentioned before still allows for Conditional Learning, vsjust R-GANs? * I could be wrong but it could be that adding the bias terms is a way of making the learning conditional on an input vector (or distribution). @corcra, @pedrofale ?

**Comment by pedrofale** [comment]
I did manage to train a conditional model while having that line commented out, so don't worry. It will work.

**Comment by corcra** [comment]
If I recall, the reason I was using my 'own' (aka modified from tensorflow) version of the RNNCell was to enable me to set the bias term while initialising the model, to let me load a pre-trained model. By default it sets the bias to some other initialisation (1 maybe?), which would make the loaded model slightly different. So, unless you're saving/loading models, that line should have no effect.

**Comment by pedrofale** [comment]
Ah, that makes sense! Thanks for clarifying. And thank you for the code, by the way.

**Comment by corcra** [comment]
No problem! I just hope it's useful!
