### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by dmortem** [ratschlab/RGAN#23]
Hi, thank you for your codes. And I wonder whether there is a pytorch version of the codes?

**Comment by corcra** [comment]
There is not, I'm afraid. We would gladly appreciate someone rewriting it in pytorch!

**Comment by dmortem** [comment]
Hi, @corcra 
I wonder why to optimize `D_logit_real` to 1 instead of `D_real`. `D_logit_real` is the output of LSTM and `D_real` = sigmoid(`D_logit_real`).
[https://github.com/ratschlab/RGAN/blob/master/experiment.py#L77](https://github.com/ratschlab/RGAN/blob/master/experiment.py#L77)

**Comment by dmortem** [comment]
My mistake, the link of the code is [https://github.com/ratschlab/RGAN/blob/master/model.py#L171](https://github.com/ratschlab/RGAN/blob/master/model.py#L171)
