### ISSUE TITLE
Hyperparameters for sine wave generation

### ISSUE THREAD

**Issue by pedrofale** [ratschlab/RGAN#4]
What are the hyperparameters used for the experiment you present in your paper for sine wave generation? I can't seem to reproduce them.

**Comment by stephenzwj** [comment]
Hi, pedrofale,

Can you run the simulation? It seems the setting file is missing

**Comment by stephenzwj** [comment]
Hi, pedrofale,

Can you run the simulation? It seems the setting file is missing

**Comment by pedrofale** [comment]
I couldn't run your code because the settings file is missing, yes. But I managed to strip down your code to the basic RGAN to be able to set it up with my own hyperparameters.

**Comment by ArturoDeza** [comment]
@pedrofale, @stephenzwj in what file should I look to get a basic demo running?

**Comment by corcra** [comment]
Hey, sorry for slow responses! 

Here's the settings file with hyperparameters and some actually-irrelevant options (sorry, the code is not very beautiful):
```
{
"settings_file": "sine_experiment",
"data": "sine",
"freq_low": 1.0,
"freq_high": 5.0,
"amplitude_low": 0.1,
"amplitude_high": 0.9,
"data_load_from": "",
"hidden_units_g": 100,
"hidden_units_d": 100,
"kappa": 1,
"latent_dim": 5,
"learning_rate": 0.1,
"batch_size": 28,
"num_epochs": 500,
"D_rounds": 1,
"G_rounds": 1,
"use_time": false,
"WGAN": false,
"WGAN_clip": false,
"identifier": "sine_experiment",
"num_generated_features": 1,
"scale": 0.1,
"normalise": false,
"cond_dim": 0,
"batch_mean": false,
"wrong_labels": false,
"max_val": 0,
"one_hot": false,
"shuffle": true,
"seq_length": 30,
"num_samples": 14000,
"num_signals": 1,
"learn_scale": false
}
```

**Comment by pedrofale** [comment]
Hello @corcra. Thank you for the file. I managed to get similar results. Thank you for your time!

**Comment by agerlach** [comment]
> But I managed to strip down the code to the basic RGAN to be able to set it up with my own hyperparameters.

@pedrofale Would you be able to make your stripped down version of the RGAN available? I didn't see anything in your repository list. Thanks.
