### ISSUE TITLE
README.md file?

### ISSUE THREAD

**Issue by ArturoDeza** [ratschlab/RGAN#5]
Was curious if there is a README file. The code looks very well commented, but not really sure where to start looking, or where the main function is!

**Comment by corcra** [comment]
There is currently no README file, unfortunately. I'll try to find a free afternoon to make a coherent one in the near future.

For now, I'll say: the "main" function is in `experiment.py`, the actual training of the model is here: https://github.com/ratschlab/RGAN/blob/master/experiment.py#L290, everything before that is preamble - loading data, parsing options, things like that. 

The data-loading functions are in `data_utils.py`, and the specification of the models (most of the tensorflow code) is in `model.py`.

Hopefully that's enough to get you started, feel free to open more issues with specific questions if you have them!

**Comment by ArturoDeza** [comment]
Sounds good, will look into it! Where could I find sample data or what is the format of the data (so I can generate sample fake data)? Other than that, I think I am good to go! Thanks

**Comment by pedrofale** [comment]
@ArturoDeza In `data_utils.py` you can find a function named `sine_wave` which generates sine waves with different amplitudes, frequencies, and phases.
