### ISSUE TITLE
test.trace.txt ?

### ISSUE THREAD

**Issue by eggachecat** [ratschlab/RGAN#9]
Thanks for the great job!
However when i run the code i got error message:
> FileNotFoundError: [Errno 2] No such file or directory: './experiments/traces/test.trace.txt'
so where is the test.trace.txt ?

**Comment by ArturoDeza** [comment]
I believe you should create an empty traces folder inside your experiments folder.

**Comment by eggachecat** [comment]
thanks @ArturoDeza

**Comment by corcra** [comment]
I just uploaded the expected folder structure with some 'dummy' files, so hopefully just cloning the repo will enable it to work out of the box!
